stages:
  - build
  - deploy
default:
  image: docker:latest
  interruptible: true
docker-build-gitlab:
  stage: build
  before_script:
    - docker login --username "${GITLAB_CONTAINER_REGISTRY_USER}" --password "${GITLAB_CONTAINER_REGISTRY_PASSWORD}" ${GITLAB_CONTAINER_REGISTRY}
  script:
    - docker build --pull --tag "${GITLAB_CONTAINER_REGISTRY_IMAGE}" .
  only:
    - master
docker-publish-gitlab:
  stage: deploy
  interruptible: false
  before_script:
    - docker login --username "${GITLAB_CONTAINER_REGISTRY_USER}" --password "${GITLAB_CONTAINER_REGISTRY_PASSWORD}" ${GITLAB_CONTAINER_REGISTRY}
  script:
    - docker push "${GITLAB_CONTAINER_REGISTRY_IMAGE}"
  only:
    - master
docker-build-docker-hub:
  stage: build
  before_script:
    - docker login --username "${DOCKER_HUB_CONTAINER_REGISTRY_USER}" --password "${DOCKER_HUB_CONTAINER_REGISTRY_PASSWORD}" ${DOCKER_HUB_CONTAINER_REGISTRY}
  script:
    - docker build --pull --tag "${DOCKER_HUB_CONTAINER_REGISTRY_IMAGE}" .
  only:
    - master
docker-publish-docker-hub:
  stage: deploy
  interruptible: false
  before_script:
    - docker login --username "${DOCKER_HUB_CONTAINER_REGISTRY_USER}" --password "${DOCKER_HUB_CONTAINER_REGISTRY_PASSWORD}" ${DOCKER_HUB_CONTAINER_REGISTRY}
  script:
    - docker push "${DOCKER_HUB_CONTAINER_REGISTRY_IMAGE}"
  only:
    - master