stages:
  - build
  - deploy
docker-build-gitlab:
  image: docker:latest
  stage: build
  before_script:
    - docker login --username "${GITLAB_REGISTRY_USER}" --password "${GITLAB_REGISTRY_PASSWORD}" ${GITLAB_REGISTRY}
  script:
    - docker build --pull --tag "${GITLAB_REGISTRY_IMAGE}" .
  only:
    - master
docker-publish-gitlab:
  image: docker:latest
  stage: deploy
  before_script:
    - docker login --username "${GITLAB_REGISTRY_USER}" --password "${GITLAB_REGISTRY_PASSWORD}" ${GITLAB_REGISTRY}
  script:
    - docker push "${GITLAB_REGISTRY_IMAGE}"
  only:
    - master
docker-build-docker-hub:
  image: docker:latest
  stage: build
  before_script:
    - docker login --username "${DOCKER_HUB_REGISTRY_USER}" --password "${DOCKER_HUB_REGISTRY_PASSWORD}" ${DOCKER_HUB_REGISTRY}
  script:
    - docker build --pull --tag "${DOCKER_HUB_REGISTRY_IMAGE}" .
  only:
    - master
docker-publish-docker-hub:
  image: docker:latest
  stage: deploy
  before_script:
    - docker login --username "${DOCKER_HUB_REGISTRY_USER}" --password "${DOCKER_HUB_REGISTRY_PASSWORD}" ${DOCKER_HUB_REGISTRY}
  script:
    - docker push "${DOCKER_HUB_REGISTRY_IMAGE}"
  only:
    - master