version: "3.4"
services:
  docker_nitrox_server:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: "unless-stopped"
    ports:
      - "11000:11000/udp" # Nitrox
    volumes:
      - "/path/to/nitrox-data:/software/nitrox" # Stores your server data, such as the configuration and world data
      - "/path/to/subnautica:/software/subnautica" # Stores Subnautica's game files - you will need to copy your own game directory here by moving the contents of your Subnautica installation directory to this volume
    environment:
      - "GROUP_ID=1000" # The ID of the group to run Nitrox as (default=1000)
      - "USER_ID=1000" # The ID of the user to run Nitrox as (default=1000)
      - "TIMEZONE=Etc/GMT" # The timezone to run Nitrox with (default=Etc/GMT)
#     - "NITROX_VERSION=1.7.0.1" # Specific version of Nitrox to install, will also disable auto-update comment out for latest version.